baseURL = 'https://silviajojo.github.io/'
languageCode = 'en-us'
title = "Silvia's Website"

theme = "toha"

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1

[params]
  defaultLanguage = "en"
  showLanguageSelector = false
  
  background = "images/default-background.jpg"
  
  [params.navbar]
    enable = true

  [params.footer]
    enable = true
    
    [params.footer.navigation]
      enable = true
      customMenus = true

    [params.footer.contactMe]
      enable = false

    [params.footer.credentials]
      enable = true

    [params.footer.disclaimer]
      enable = true
      text = "The opinions expressed on this site are my own personal opinions and do not represent my employer's view in any way."

  [params.assets]
    favicon = "images/site/favicon.png"
    customCSS = ["css/custom.css"]
    customJS = ["js/custom.js"]

  [params.topNavbar]
    maxVisibleSections = 5

  [params.features]
    [params.features.theme]
      enable = true
      
      [params.features.theme.services]
        light = true
        dark = true
        default = "system"

    [params.features.portfolio]
      enable = true

    [params.features.blog]
      enable = true
      showAuthor = true
      
      [params.features.blog.shareButtons]
        facebook = true
        twitter = true
        linkedin = true
        reddit = true
        whatsapp = true
        email = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

# Use Hugo modules to add theme
[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"
