baseURL = 'https://silviajojo.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "toha"

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.zh]
    languageName = "中文"
    weight = 2

[params]
  defaultLanguage = "en"
  showLanguageSelector = true
  
  background = "images/default-background.jpg"
  
  [params.navbar]
    enable = true

  [params.footer]
    enable = true

  [params.assets]
    favicon = "images/site/favicon.png"
    customCSS = ["css/custom.css"]
    customJS = ["js/custom.js"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Use Hugo modules to add theme
[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"